pragma solidity ^0.4.24;

library Items {
    enum State 
    { 
      NoState,
      ComponentsManufactured,
      SmartphoneAssembled,
      ShippedToRetailer,
      ReceivedByRetailer,
      OnSale,
      Sold,
      ShippedToConsumer,
      ReceivedByConsumer
    }
    struct Item {
        uint    sku;  // Stock Keeping Unit (SKU)
        uint    upc; // Universal Product Code (UPC), generated by the Farmer, goes on the package, can be verified by the Consumer
        address ownerID;  // Metamask-Ethereum address of the current owner as the product moves through 8 stages
        address originID; // Metamask-Ethereum address of the Farmer
        uint    productID;  // Product ID potentially a combination of upc + sku
        string  productNotes; // Product Notes
        uint    price; // Product Price
        State   itemState;  // Product State as represented in the enum above
        address smartphoneMakerID;
        address retailerID; // Metamask-Ethereum address of the Retailer
        address consumerID; // Metamask-Ethereum address of the Consumer
    }
}